.TH attach 1
.SH NAME
.B attach
\- reads the output of a background process
.SH SYNOPSIS
.B attach
SOCKET
.SH DESCRIPTION
Prints the output of a background process.

The first command-line argument is the path passed to
.B detachd(1),
at the process creation time.
.SH SIGNALS
.TP
.B SIGTERM or SIGINT
Stops the process
.SH "SEE ALSO"
.B detachd(1)
.SH AUTHOR
Dima Krasner (dima@dimakrasner.com)
