.TH chroot 8
.SH NAME
.B chroot
\- runs a command with a given file system root
.SH SYNOPSIS
.B chroot
DIRECTORY
ARGUMENT...
.SH DESCRIPTION
Changes the file system root to a given directory and executes a command.
.SH "SEE ALSO"
.B mount(8), umount(8)
.SH AUTHOR
Dima Krasner (dima@dimakrasner.com)
