.TH devd 8
.SH NAME
.B devd
\- automatically loads kernel modules
.SH SYNOPSIS
.B devd
.SH DESCRIPTION
Automatically loads the most appropriate drivers for newly-recognized hardware.
.SH SIGNALS
.TP
.B SIGTERM
Stops the process
.SH "SEE ALSO"
.B insmod(8), modprobe(8), syslogd(8)
.SH AUTHOR
Dima Krasner (dima@dimakrasner.com)
