.TH head 1
.SH NAME
.B head
\- filter the top
.SH SYNOPSIS
.B head
OPTIONS n
.SH DESCRIPTION
Filters the beginning of data written to standard input.
.TP
.B -n
Filter the first
.B n
lines
.TP
.B -c
Filter the first
.B n
bytes
.SH "SEE ALSO"
.B echo(1), tee(1), cat(1), cp(1)
.SH AUTHOR
Dima Krasner (dima@dimakrasner.com)
