.TH init 8
.SH NAME
.B init
\- controls the system state
.SH SYNOPSIS
.B init
.SH DESCRIPTION
Manages system events and takes care of startup and shutdown procedures.
.SH FILES
.TP
.B /etc/init.d/startup
The system startup script
.TP
.B /etc/init.d/shutdown
The system shutdown script
.SH "SEE ALSO"
.B poweroff(8), reboot(8)
.SH AUTHOR
Dima Krasner (dima@dimakrasner.com)
