.TH insmod 8
.SH NAME
.B insmod
\- loads a single kernel module
.SH SYNOPSIS
.B insmod
PATH
.SH DESCRIPTION
Loads a single kernel module.
.SH FILES
.TP
.B /lib/modules
The directory containing all kernel modules
.SH "SEE ALSO"
.B rmmod(8), modprobe(8), kmoduled(8), lsmod(8), modinfo(8), depmod(8),
.B syslogd(8)
.SH AUTHOR
Dima Krasner (dima@dimakrasner.com)
