.TH mktemp 1
.SH NAME
.B mktemp
\- creates a temporary file
.SH SYNOPSIS
.B mktemp
[-d]
.SH DESCRIPTION
Creates a new, temporary file under /tmp.
.TP
.B -d
When this option is specified, a directory is created instead of a regular file.
.SH FILES
.TP
.B /tmp
A directory for temporary files
.SH AUTHOR
Dima Krasner (dima@dimakrasner.com)
