.TH modprobe 8
.SH NAME
.B modprobe
\- loads a kernel module
.SH SYNOPSIS
.B modprobe
NAME
.SH DESCRIPTION
Loads a kernel module with its dependencies.
.TP
.B -q
Supresses logging.
.SH "SEE ALSO"
.B insmod(8), kmoduled(8), rmmod(8), lsmod(8), modinfo(8), depmod(8), syslogd(8)
.SH AUTHOR
Dima Krasner (dima@dimakrasner.com)
