.TH relayd 8
.SH NAME
.B relayd
\- a TCP server
.SH SYNOPSIS
.B relayd
LOCAL_PORT ARG1 ARG2 [HANDLER]
.SH DESCRIPTION
Listens on a given port and runs an external handler program (which accepts two arguments) for each incoming client.

If no handler program is specified, relayd falls back to
.B
client(1).
.SH SIGNALS
.TP
.B SIGTERM
Stops the process
.SH "SEE ALSO"
.B client(1), echo(1)
.SH AUTHOR
Dima Krasner (dima@dimakrasner.com)
