.TH relayd 8
.SH NAME
.B relayd
\- relays TCP sessions to a server
.SH SYNOPSIS
.B relayd
LOCAL_PORT SERVER REMOTE_PORT
.SH DESCRIPTION
Listens on a given port and redirects all incoming traffic to a given server.
.SH SIGNALS
.TP
.B SIGTERM
Stops the process
.SH "SEE ALSO"
.B client(1)
.SH AUTHOR
Dima Krasner (dima@dimakrasner.com)
