.TH sulogin 1
.SH NAME
.B sulogin
\- starts a session
.SH SYNOPSIS
.B sulogin
[USER]
.SH DESCRIPTION
Starts a session, by showing a user and password prompt. Once the user is
authenticated, an interactive shell is executed.

If no user name is specified as part of the command-line, the shell is executed
as a login shell (i.e with "-l").
.SH FILES
.TP
.B /etc/passwd
Specifies each user's home directory and shell
.TP
.B /etc/shadow
Specifies each user's password hash
.TP
.B /etc/issue
A file shown before a login prompt
.TP
.B /etc/motd
A file shown after a user authenticates through a login prompt
.SH ENVIRONMENT VARIABLES
.TP
.B TERM
The value of TERM is inherited by the shell; if this environment variable does
not exist, its is initialized with "linux"
.TP
.B HOME
The value of HOME is set to the user's home directory
.SH AUTHOR
Dima Krasner (dima@dimakrasner.com)
