.TH syslogd 8
.SH NAME
.B syslogd
\- manages the system log
.SH SYNOPSIS
.B syslogd PATH
.SH DESCRIPTION
Writes system log messages to a given file.
.SH SIGNALS
.TP
.B SIGTERM
Stops the process
.SH "SEE ALSO"
.B logd(8), dmesg(1), logger(1), klogecho(8)
.SH AUTHOR
Dima Krasner (dima@dimakrasner.com)
