.TH syslogd 8
.SH NAME
.B syslogd
\- manages the system log
.SH SYNOPSIS
.B syslogd
.SH DESCRIPTION
Manages the system log.
.SH FILES
.TP
.B /run/messages
A named pipe the system log messages are written to
.SH SIGNALS
.TP
.B SIGTERM
Stops the process
.SH "SEE ALSO"
.B logd(8), logger(1)
.SH AUTHOR
Dima Krasner (dima@dimakrasner.com)
