.TH uname 1
.SH NAME
.B uname
\- displays operating system information
.SH SYNOPSIS
.B uname
OPTION...
.SH DESCRIPTION
Prints operating system information.
.TP
.B -a
Shows all information
.TP
.B -s
Shows the kernel name
.TP
.B -r
Shows the kernel release
.TP
.B -v
Shows the kernel version
.TP
.B -m
Shows the hardware type
.SH "SEE ALSO"
.B hostname(1)
.SH AUTHOR
Dima Krasner (dima@dimakrasner.com)
