.TH waitmax 1
.SH NAME
.B waitmax
\- run a process with a timeout
.SH SYNOPSIS
.B waitmax
TIMEOUT COMMAND
.SH DESCRIPTION
Runs a process with a timeout; if the process continues to run until the timeout
has expired, it is killed.
.SH "SEE ALSO"
.B kill(1)
.SH AUTHOR
Dima Krasner (dima@dimakrasner.com)
