.TH autologin 1
.SH NAME
.B autologin
\- logs in automatically
.SH SYNOPSIS
.B autologin
[USER]
.SH DESCRIPTION
Automatically logs in a user and runs an interactive shell.
.SH FILES
.TP
.B /etc/issue
A text file printed before the user is logged in
.TP
.B /etc/motd
A text file printed after the user is logged in
.SH AUTHOR
Dima Krasner (dima@dimakrasner.com)
